
---

- name: Check if the "bmctl" Configuration YAML File Exists
  ansible.builtin.stat:
    path: "{{ bmctl_workspace_dir }}/{{ cluster_name }}/{{ cluster_name }}.yaml"
  register: bmctl_config_exists

- name: Create the Standard Workspace for a "NEW" Anthos Cluster
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      export GOOGLE_APPLICATION_CREDENTIALS="{{ bmctl_workspace_dir }}/{{ ansible_service_account }}.json"
      bmctl create config -c "{{ cluster_name }}" --quiet
  args:
    executable: /bin/bash
  register: create_config
  failed_when: false
  changed_when: false
  when: not bmctl_config_exists.stat.exists

- name: Check the Previous Task
  ansible.builtin.debug:
    msg: "{{ create_config.stdout_lines + create_config.stderr_lines }}"
  failed_when: create_config.rc != 0
  when:
    - create_config.stdout_lines is defined
    - create_config.stderr_lines is defined

# - name: kubectl generate cluster-role rbac policy
#   ansible.builtin.shell:
#     cmd: |
#       set -o pipefail
#       mkdr baremetal
#   args:
#     executable: /bin/bash


- name: Write the "bmctl" Configuration YAML File
  ansible.builtin.template:
    src: bmctl-config-{{ cluster_name }}.yaml.j2
    dest: "{{ bmctl_workspace_dir }}/{{ cluster_name }}/{{ cluster_name }}.yaml"
    owner: "{{ login_user }}"
    group: "{{ login_user }}"
    mode: u=rw,g=rw,o=r