---

- name: Install Dependencies [Debian / Ubuntu]
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg

- name: Add Google Cloud SDK Package Repository Source [Debian / Ubuntu]
  ansible.builtin.template:
    src: google-cloud-sdk.list.j2
    dest: /etc/apt/sources.list.d/google-cloud-sdk.list
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Import the Google Cloud Package Repository GPG Key [Debian / Ubuntu]
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
  args:
    executable: /bin/bash
  changed_when: false

- name: Install Google Cloud SDK [Debian / Ubuntu]
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - google-cloud-sdk
