---

- name: Remove Unwanted Time Synchronisation Packages [RedHat / CentOS]
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: absent
  with_items:
    - ntp
    - systemd-timesyncd

- name: Remove Packages Dependencies No Longer Required [RedHat / CentOS]
  ansible.builtin.dnf:
    autoremove: yes

- name: Install Time Synchronisation Packages [RedHat / CentOS]
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - chrony

- name: Enable Time Synchronisation Service [RedHat / CentOS]
  ansible.builtin.systemd:
    name: chronyd
    enabled: yes

- name: Configure Time Synchronisation Service [RedHat / CentOS]
  ansible.builtin.template:
    src: chrony.conf.j2
    dest: /etc/chrony.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  register: configuration

- name: Restart Time Synchronisation Service [RedHat / CentOS]
  ansible.builtin.systemd:
    name: chronyd
    state: restarted
  when: configuration.changed
  tags: ['skip_ansible_lint']
