---

- name: Update All Packages to the Latest Version [Debian / Ubuntu]
  ansible.builtin.apt:
    update_cache: yes
    upgrade: dist
    state: latest
  register: update_packages

- name: Remove Packages Dependencies No Longer Required [Debian / Ubuntu]
  ansible.builtin.apt:
    autoremove: yes

- name: Reboot and Wait [Debian / Ubuntu]
  ansible.builtin.reboot:
    msg: "Reboot Initiated by Ansible"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami
  become: true
  when: update_packages.changed
  tags: ['skip_ansible_lint']
