---

- name: Update All Packages to the Latest Version [RedHat / CentOS]
  ansible.builtin.dnf:
    update_cache: yes
    name:  "*"
    state: latest
  register: update_packages

- name: Remove Packages Dependencies No Longer Required [RedHat / CentOS]
  ansible.builtin.dnf:
    autoremove: yes

- name: Reboot and Wait [RedHat / CentOS]
  ansible.builtin.reboot:
    msg: "Reboot Initiated by Ansible"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami
  become: true
  when: update_packages.changed
  tags: ['skip_ansible_lint']
