---

- name: Retrieve Latest Ansible Service Account Key from Secret Manager
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      gcloud secrets versions access latest --secret="{{ item }}"
  args:
    executable: /bin/bash
  # delegate_to: localhost
  delegate_to: "{{ target_workstation }}"
  register: out
  changed_when: false
  with_items:
    - "{{ copy_service_account_key }}"

- name: Copy Ansible Service Account Key
  ansible.builtin.copy:
    content: "{{ out.results[0].stdout }}"
    dest: "{{ gcp_keys_dir }}/{{ item }}.json"
    owner: "{{ login_user }}"
    group: "{{ login_user }}"
    mode: u=rw,g=,o=
  when: out.results is defined and (out.results | length > 0)
  with_items:
    - "{{ copy_service_account_key }}"
